/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 24 04:45:14 GMT 2026
 */

package ar.edu.unrc.game2048;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ar.edu.unrc.game2048.AddTileDeterministic;
import ar.edu.unrc.game2048.AddTileStrategy;
import ar.edu.unrc.game2048.Board;
import ar.edu.unrc.game2048.Cell;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class Board_ESTest extends Board_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(4, 4);
      Board.Position board_Position1 = new Board.Position(3, 0);
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertEquals(3, board_Position1.row);
      assertEquals(4, board_Position0.col);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      AddTileDeterministic addTileDeterministic0 = new AddTileDeterministic();
      Board board0 = new Board(3, addTileDeterministic0);
      boolean boolean0 = board0.repOK();
      assertEquals(3, board0.getSize());
      assertTrue(boolean0);
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      AddTileDeterministic addTileDeterministic0 = new AddTileDeterministic();
      Board board0 = new Board(3, addTileDeterministic0);
      String string0 = board0.toString();
      assertTrue(board0.repOK());
      assertEquals("Score: 0\n+-----+-----+-----+\n|     |     |     |\n+-----+-----+-----+\n|    2|     |     |\n+-----+-----+-----+\n|     |    2|     |\n+-----+-----+-----+\n", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      AddTileDeterministic addTileDeterministic0 = new AddTileDeterministic();
      Board board0 = new Board(1, addTileDeterministic0);
      board0.hashCode();
      assertEquals(1, board0.getSize());
      assertTrue(board0.repOK());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      AddTileDeterministic addTileDeterministic0 = new AddTileDeterministic();
      Board board0 = new Board(3, addTileDeterministic0);
      boolean boolean0 = board0.isWinningBoard();
      assertEquals(3, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell(3, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (3, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Board board0 = new Board(1);
      boolean boolean0 = board0.moveRight();
      assertEquals(0, board0.getScore());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Board board0 = new Board(1);
      boolean boolean0 = board0.moveLeft();
      assertEquals(1, board0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      AddTileDeterministic addTileDeterministic0 = new AddTileDeterministic();
      Board board0 = new Board(1, addTileDeterministic0);
      boolean boolean0 = board0.moveDown();
      assertFalse(boolean0);
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Board board0 = new Board(1);
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertEquals(0, board0.getScore());
      assertTrue(set0.isEmpty());
      assertTrue(board0.repOK());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = board0.getCell(0, 0);
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      assertEquals(".", cell0.toString());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = Cell.EMPTY;
      // Undeclared exception!
      try { 
        board0.setCell(4, 4, cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((Board) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      AddTileDeterministic addTileDeterministic0 = new AddTileDeterministic();
      Board board0 = new Board(716, addTileDeterministic0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Board board0 = new Board(1573);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: 0
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      AddTileDeterministic addTileDeterministic0 = new AddTileDeterministic();
      Board board0 = new Board(3, addTileDeterministic0);
      Board board1 = new Board(board0);
      assertTrue(board1.equals((Object)board0));
      
      board0.moveLeft();
      boolean boolean0 = board1.equals(board0);
      assertFalse(board1.equals((Object)board0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.equals(board0);
      assertTrue(boolean0);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.hasEmptyCells();
      assertEquals(4, board0.getSize());
      assertTrue(boolean0);
      assertTrue(board0.repOK());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      AddTileDeterministic addTileDeterministic0 = new AddTileDeterministic();
      Board board0 = new Board(3, addTileDeterministic0);
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertTrue(board0.repOK());
      assertEquals(7, set0.size());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Board board0 = new Board(3);
      Cell cell0 = Cell.EMPTY;
      board0.setCell(0, 0, cell0);
      assertEquals(3, board0.getSize());
      assertTrue(board0.repOK());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      AddTileDeterministic addTileDeterministic0 = new AddTileDeterministic();
      Board board0 = new Board(3, addTileDeterministic0);
      Board board1 = new Board(board0);
      boolean boolean0 = board1.equals(board0);
      assertTrue(boolean0);
      assertEquals(3, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Board board0 = new Board();
      int int0 = board0.getSize();
      assertEquals(4, int0);
      assertTrue(board0.repOK());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-1915), (-1885));
      Board.Position board_Position1 = new Board.Position((-1915), (-1885));
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertTrue(boolean0);
      assertEquals((-1885), board_Position1.col);
      assertEquals((-1915), board_Position1.row);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(3, 738);
      Board.Position board_Position1 = new Board.Position(3, (-837));
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertEquals(3, board_Position1.row);
      assertFalse(boolean0);
      assertFalse(board_Position1.equals((Object)board_Position0));
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Board board0 = new Board();
      Board.Position board_Position0 = new Board.Position(2522, 4);
      boolean boolean0 = board_Position0.equals(board0);
      assertEquals(4, board_Position0.col);
      assertEquals(2522, board_Position0.row);
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-3277), 0);
      boolean boolean0 = board_Position0.equals((Object) null);
      assertEquals((-3277), board_Position0.row);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-1915), (-1885));
      boolean boolean0 = board_Position0.equals(board_Position0);
      assertEquals((-1915), board_Position0.row);
      assertEquals((-1885), board_Position0.col);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(1, 4);
      Board.Position board_Position1 = new Board.Position(4, 1);
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertEquals(1, board_Position1.col);
      assertEquals(4, board_Position1.row);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(5);
      boolean boolean0 = board0.equals(board1);
      assertFalse(boolean0);
      assertTrue(board1.repOK());
      assertEquals(0, board1.getScore());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Board board0 = new Board();
      board0.equals("(2522, 4)");
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.equals((Object) null);
      assertEquals(0, board0.getScore());
      assertFalse(boolean0);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Board board0 = new Board(1);
      boolean boolean0 = board0.isFull();
      assertTrue(boolean0);
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.isFull();
      assertTrue(board0.repOK());
      assertFalse(boolean0);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      AddTileDeterministic addTileDeterministic0 = new AddTileDeterministic();
      Board board0 = new Board(1, addTileDeterministic0);
      boolean boolean0 = board0.isLosingBoard();
      assertTrue(boolean0);
      assertTrue(board0.repOK());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.isLosingBoard();
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell(0, 31);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 31) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell(0, (-1));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, -1) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Board board0 = new Board(3);
      // Undeclared exception!
      try { 
        board0.getCell(810, 3);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (810, 3) is out of bounds for board size 3
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Board board0 = new Board(2);
      // Undeclared exception!
      try { 
        board0.getCell((-1051), 327);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-1051, 327) is out of bounds for board size 2
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.setCell(0, 0, (Cell) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell cannot be null
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      AddTileDeterministic addTileDeterministic0 = new AddTileDeterministic();
      Board board0 = null;
      try {
        board0 = new Board((-1915), addTileDeterministic0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -1915
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Board board0 = new Board();
      board0.moveDown();
      board0.moveUp();
      boolean boolean0 = board0.moveUp();
      assertEquals(4, board0.getScore());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Board board0 = new Board();
      board0.moveLeft();
      board0.moveRight();
      int int0 = board0.getScore();
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Board board0 = new Board();
      int int0 = board0.getScore();
      assertTrue(board0.repOK());
      assertEquals(0, int0);
      assertEquals(4, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.moveUp();
      assertTrue(boolean0);
      
      Cell cell0 = board0.getCell(0, 0);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertEquals(2, cell0.getValue());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Board board0 = new Board();
      board0.moveRight();
      board0.moveUp();
      boolean boolean0 = board0.repOK();
      assertEquals(4, board0.getScore());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(2522, 4);
      String string0 = board_Position0.toString();
      assertEquals("(2522, 4)", string0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board(3, (AddTileStrategy) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }
}
