/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 25 20:05:32 GMT 2026
 */

package ar.edu.unrc.game2048;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ar.edu.unrc.game2048.AddRandomTile;
import ar.edu.unrc.game2048.AddTileDeterministic;
import ar.edu.unrc.game2048.AddTileStrategy;
import ar.edu.unrc.game2048.Board;
import ar.edu.unrc.game2048.Cell;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class Board_ESTest extends Board_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Board board0 = new Board();
      assertNotNull(board0);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      boolean boolean0 = board0.isFull();
      assertFalse(boolean0);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      boolean boolean1 = board0.isLosingBoard();
      assertTrue(boolean1 == boolean0);
      assertFalse(boolean1);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      Board board1 = new Board(board0);
      assertTrue(board1.equals((Object)board0));
      assertNotNull(board1);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertTrue(board1.repOK());
      assertFalse(board1.isWinningBoard());
      assertEquals(4, board1.getSize());
      assertEquals(0, board1.getScore());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean2 = board1.isWinningBoard();
      assertTrue(board0.equals((Object)board1));
      assertTrue(board1.equals((Object)board0));
      assertTrue(boolean2 == boolean0);
      assertTrue(boolean2 == boolean1);
      assertNotSame(board0, board1);
      assertNotSame(board1, board0);
      assertFalse(boolean2);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertTrue(board1.repOK());
      assertFalse(board1.isWinningBoard());
      assertEquals(4, board1.getSize());
      assertEquals(0, board1.getScore());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean3 = board1.moveRight();
      assertFalse(board0.equals((Object)board1));
      assertFalse(board1.equals((Object)board0));
      assertFalse(boolean3 == boolean0);
      assertFalse(boolean3 == boolean1);
      assertFalse(boolean3 == boolean2);
      assertNotSame(board0, board1);
      assertNotSame(board1, board0);
      assertTrue(boolean3);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertTrue(board1.repOK());
      assertFalse(board1.isWinningBoard());
      assertEquals(4, board1.getSize());
      assertEquals(0, board1.getScore());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      Board.Position board_Position0 = new Board.Position(4, (-2660));
      assertNotNull(board_Position0);
      assertEquals(4, board_Position0.row);
      assertEquals((-2660), board_Position0.col);
      
      board1.hashCode();
      assertFalse(board0.equals((Object)board1));
      assertFalse(board1.equals((Object)board0));
      assertNotSame(board0, board1);
      assertNotSame(board1, board0);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertTrue(board1.repOK());
      assertFalse(board1.isWinningBoard());
      assertEquals(4, board1.getSize());
      assertEquals(0, board1.getScore());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      String string0 = board_Position0.toString();
      assertEquals("(4, -2660)", string0);
      assertNotNull(string0);
      assertEquals(4, board_Position0.row);
      assertEquals((-2660), board_Position0.col);
      
      String string1 = board_Position0.toString();
      assertTrue(string1.equals((Object)string0));
      assertEquals("(4, -2660)", string1);
      assertNotNull(string1);
      assertEquals(4, board_Position0.row);
      assertEquals((-2660), board_Position0.col);
      
      String string2 = board_Position0.toString();
      assertTrue(string2.equals((Object)string0));
      assertTrue(string2.equals((Object)string1));
      assertEquals("(4, -2660)", string2);
      assertNotNull(string2);
      assertEquals(4, board_Position0.row);
      assertEquals((-2660), board_Position0.col);
      
      boolean boolean4 = board_Position0.equals(board1);
      assertFalse(board0.equals((Object)board1));
      assertFalse(board1.equals((Object)board0));
      assertFalse(boolean4 == boolean3);
      assertTrue(boolean4 == boolean0);
      assertTrue(boolean4 == boolean1);
      assertTrue(boolean4 == boolean2);
      assertNotSame(board0, board1);
      assertNotSame(board1, board0);
      assertFalse(boolean4);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertTrue(board1.repOK());
      assertFalse(board1.isWinningBoard());
      assertEquals(4, board1.getSize());
      assertEquals(0, board1.getScore());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(4, board_Position0.row);
      assertEquals((-2660), board_Position0.col);
      
      boolean boolean5 = board0.equals(board1);
      assertFalse(board0.equals((Object)board1));
      assertFalse(board1.equals((Object)board0));
      assertTrue(boolean5 == boolean0);
      assertTrue(boolean5 == boolean2);
      assertTrue(boolean5 == boolean4);
      assertTrue(boolean5 == boolean1);
      assertFalse(boolean5 == boolean3);
      assertNotSame(board0, board1);
      assertNotSame(board1, board0);
      assertFalse(boolean5);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertTrue(board1.repOK());
      assertFalse(board1.isWinningBoard());
      assertEquals(4, board1.getSize());
      assertEquals(0, board1.getScore());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean6 = board0.isLosingBoard();
      assertFalse(board0.equals((Object)board1));
      assertFalse(boolean6 == boolean3);
      assertTrue(boolean6 == boolean5);
      assertTrue(boolean6 == boolean0);
      assertTrue(boolean6 == boolean1);
      assertTrue(boolean6 == boolean2);
      assertTrue(boolean6 == boolean4);
      assertNotSame(board0, board1);
      assertFalse(boolean6);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      boolean boolean7 = board0.isLosingBoard();
      assertFalse(board0.equals((Object)board1));
      assertTrue(boolean7 == boolean2);
      assertTrue(boolean7 == boolean0);
      assertTrue(boolean7 == boolean1);
      assertTrue(boolean7 == boolean4);
      assertFalse(boolean7 == boolean3);
      assertTrue(boolean7 == boolean6);
      assertTrue(boolean7 == boolean5);
      assertNotSame(board0, board1);
      assertFalse(boolean7);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      boolean boolean8 = board0.hasEmptyCells();
      assertFalse(board0.equals((Object)board1));
      assertFalse(boolean8 == boolean6);
      assertFalse(boolean8 == boolean1);
      assertTrue(boolean8 == boolean3);
      assertFalse(boolean8 == boolean5);
      assertFalse(boolean8 == boolean4);
      assertFalse(boolean8 == boolean2);
      assertFalse(boolean8 == boolean7);
      assertFalse(boolean8 == boolean0);
      assertNotSame(board0, board1);
      assertTrue(boolean8);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      Set<Board.Position> set0 = board1.getEmptyPositions();
      assertFalse(board0.equals((Object)board1));
      assertFalse(board1.equals((Object)board0));
      assertNotSame(board0, board1);
      assertNotSame(board1, board0);
      assertNotNull(set0);
      assertFalse(set0.isEmpty());
      assertEquals(13, set0.size());
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertTrue(board1.repOK());
      assertFalse(board1.isWinningBoard());
      assertEquals(4, board1.getSize());
      assertEquals(0, board1.getScore());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(set0.contains(board_Position0));
      
      // Undeclared exception!
      try { 
        board0.getCell(4, 315);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, 315) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Board board0 = new Board(29);
      assertNotNull(board0);
      assertFalse(board0.isWinningBoard());
      assertEquals(29, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean0 = board0.moveDown();
      assertTrue(boolean0);
      assertFalse(board0.isWinningBoard());
      assertEquals(29, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean1 = board0.isFull();
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
      assertFalse(board0.isWinningBoard());
      assertEquals(29, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertNotNull(set0);
      assertFalse(board0.isWinningBoard());
      assertEquals(29, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(838, set0.size());
      assertFalse(set0.isEmpty());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean2 = board0.moveLeft();
      assertFalse(boolean2 == boolean1);
      assertTrue(boolean2 == boolean0);
      assertTrue(boolean2);
      assertFalse(board0.isWinningBoard());
      assertEquals(29, board0.getSize());
      assertEquals(4, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      Set<Board.Position> set1 = board0.getEmptyPositions();
      assertFalse(set1.equals((Object)set0));
      assertNotSame(set1, set0);
      assertNotNull(set1);
      assertEquals(29, board0.getSize());
      assertEquals(4, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(838, set1.size());
      assertFalse(set1.isEmpty());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      board0.moveDown();
      Random.setNextRandom(5575);
      Board.Direction board_Direction0 = Board.Direction.LEFT;
      board0.moveDown();
      board0.getEmptyPositions();
      board0.isLosingBoard();
      board0.isFull();
      board0.isWinningBoard();
      board0.getEmptyPositions();
      board0.isWinningBoard();
      board0.toString();
      board0.getSize();
      board0.getSize();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Board board0 = new Board();
      assertNotNull(board0);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      Board board1 = new Board(board0);
      assertTrue(board1.equals((Object)board0));
      assertNotNull(board1);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertTrue(board1.repOK());
      assertFalse(board1.isWinningBoard());
      assertEquals(4, board1.getSize());
      assertEquals(0, board1.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean0 = board1.equals(board0);
      assertTrue(board0.equals((Object)board1));
      assertTrue(board1.equals((Object)board0));
      assertNotSame(board0, board1);
      assertNotSame(board1, board0);
      assertTrue(boolean0);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertTrue(board1.repOK());
      assertFalse(board1.isWinningBoard());
      assertEquals(4, board1.getSize());
      assertEquals(0, board1.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      // Undeclared exception!
      try { 
        board0.getCell(4, (-2784));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, -2784) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Board board0 = new Board(1);
      assertNotNull(board0);
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean0 = board0.isFull();
      assertTrue(boolean0);
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean1 = board0.moveLeft();
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      board0.hashCode();
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean2 = board0.isFull();
      assertFalse(boolean2 == boolean1);
      assertTrue(boolean2 == boolean0);
      assertTrue(boolean2);
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean3 = board0.moveRight();
      assertFalse(boolean3 == boolean2);
      assertFalse(boolean3 == boolean0);
      assertTrue(boolean3 == boolean1);
      assertFalse(boolean3);
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      Cell cell0 = Cell.EMPTY;
      assertNotNull(cell0);
      assertEquals(".", cell0.toString());
      assertTrue(cell0.isEmpty());
      assertEquals(0, cell0.getValue());
      assertTrue(cell0.repOK());
      
      boolean boolean4 = board0.moveDown();
      assertTrue(boolean4 == boolean1);
      assertTrue(boolean4 == boolean3);
      assertFalse(boolean4 == boolean0);
      assertFalse(boolean4 == boolean2);
      assertFalse(boolean4);
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      // Undeclared exception!
      try { 
        board0.getCell(4, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, 4) is out of bounds for board size 1
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Board board0 = new Board();
      assertNotNull(board0);
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      boolean boolean0 = board0.moveRight();
      assertTrue(boolean0);
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      String string0 = "bzlZpm";
      boolean boolean1 = board0.moveRight();
      assertTrue(boolean1 == boolean0);
      assertTrue(boolean1);
      assertEquals(4, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      boolean boolean2 = board0.isFull();
      assertFalse(boolean2 == boolean0);
      assertFalse(boolean2 == boolean1);
      assertFalse(boolean2);
      assertEquals(4, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertNotNull(set0);
      assertEquals(4, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(set0.isEmpty());
      assertEquals(13, set0.size());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      board0.hashCode();
      assertEquals(4, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      boolean boolean3 = board0.moveUp();
      assertTrue(boolean3 == boolean0);
      assertFalse(boolean3 == boolean2);
      assertTrue(boolean3 == boolean1);
      assertTrue(boolean3);
      assertEquals(4, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      int int0 = (-510);
      int int1 = 1158;
      Cell cell0 = board0.getCell(0, 0);
      assertNotNull(cell0);
      assertEquals(4, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertEquals(2, cell0.getValue());
      assertEquals("2", cell0.toString());
      assertFalse(cell0.isEmpty());
      assertTrue(cell0.repOK());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      // Undeclared exception!
      try { 
        board0.getCell(2048, (-554));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2048, -554) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Board board0 = new Board(3);
      assertNotNull(board0);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(3, board0.getSize());
      assertTrue(board0.repOK());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      board0.hashCode();
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(3, board0.getSize());
      assertTrue(board0.repOK());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Board board0 = new Board(1);
      assertNotNull(board0);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean0 = board0.moveLeft();
      assertFalse(boolean0);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      int int0 = (-1006);
      Board.Position board_Position0 = new Board.Position(717, (-1006));
      assertNotNull(board_Position0);
      assertEquals((-1006), board_Position0.col);
      assertEquals(717, board_Position0.row);
      
      boolean boolean1 = board0.moveLeft();
      assertTrue(boolean1 == boolean0);
      assertFalse(boolean1);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean2 = board0.moveUp();
      assertTrue(boolean2 == boolean1);
      assertTrue(boolean2 == boolean0);
      assertFalse(boolean2);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      String string0 = board_Position0.toString();
      assertEquals("(717, -1006)", string0);
      assertNotNull(string0);
      assertEquals((-1006), board_Position0.col);
      assertEquals(717, board_Position0.row);
      
      String string1 = board_Position0.toString();
      assertTrue(string1.equals((Object)string0));
      assertEquals("(717, -1006)", string1);
      assertNotNull(string1);
      assertEquals((-1006), board_Position0.col);
      assertEquals(717, board_Position0.row);
      
      String string2 = board_Position0.toString();
      assertTrue(string2.equals((Object)string0));
      assertTrue(string2.equals((Object)string1));
      assertEquals("(717, -1006)", string2);
      assertNotNull(string2);
      assertEquals((-1006), board_Position0.col);
      assertEquals(717, board_Position0.row);
      
      String string3 = board_Position0.toString();
      assertTrue(string3.equals((Object)string2));
      assertTrue(string3.equals((Object)string1));
      assertTrue(string3.equals((Object)string0));
      assertEquals("(717, -1006)", string3);
      assertNotNull(string3);
      assertEquals((-1006), board_Position0.col);
      assertEquals(717, board_Position0.row);
      
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertNotNull(set0);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(set0.isEmpty());
      assertEquals(0, set0.size());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(set0.contains(board_Position0));
      
      String string4 = "*sr\\-`?@\\\\";
      String string5 = board0.toString();
      assertFalse(string5.equals((Object)string0));
      assertFalse(string5.equals((Object)string4));
      assertFalse(string5.equals((Object)string1));
      assertFalse(string5.equals((Object)string2));
      assertFalse(string5.equals((Object)string3));
      assertEquals("Score: 0\n+-----+\n|    2|\n+-----+\n", string5);
      assertNotNull(string5);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean3 = board0.isLosingBoard();
      assertFalse(boolean3 == boolean0);
      assertFalse(boolean3 == boolean1);
      assertFalse(boolean3 == boolean2);
      assertTrue(boolean3);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      // Undeclared exception!
      try { 
        board0.getCell((-1006), (-1006));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-1006, -1006) is out of bounds for board size 1
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, 3);
      assertNotNull(board_Position0);
      assertEquals(0, board_Position0.row);
      assertEquals(3, board_Position0.col);
      
      Board board0 = new Board(3);
      assertNotNull(board0);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(3, board0.getSize());
      assertEquals(0, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean0 = board0.moveDown();
      assertTrue(boolean0);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(3, board0.getSize());
      assertEquals(0, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean1 = board0.isLosingBoard();
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(3, board0.getSize());
      assertEquals(0, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      String string0 = board_Position0.toString();
      assertEquals("(0, 3)", string0);
      assertNotNull(string0);
      assertEquals(0, board_Position0.row);
      assertEquals(3, board_Position0.col);
      
      boolean boolean2 = board0.moveRight();
      assertTrue(boolean2 == boolean0);
      assertFalse(boolean2 == boolean1);
      assertTrue(boolean2);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(3, board0.getSize());
      assertEquals(4, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean3 = board0.moveLeft();
      assertTrue(boolean3 == boolean2);
      assertTrue(boolean3 == boolean0);
      assertFalse(boolean3 == boolean1);
      assertTrue(boolean3);
      assertFalse(board0.isWinningBoard());
      assertEquals(8, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(3, board0.getSize());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean4 = board0.moveDown();
      assertFalse(boolean4 == boolean1);
      assertTrue(boolean4 == boolean3);
      assertTrue(boolean4 == boolean2);
      assertTrue(boolean4 == boolean0);
      assertTrue(boolean4);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(3, board0.getSize());
      assertEquals(16, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean5 = board0.isLosingBoard();
      assertFalse(boolean5 == boolean3);
      assertTrue(boolean5 == boolean1);
      assertFalse(boolean5 == boolean0);
      assertFalse(boolean5 == boolean2);
      assertFalse(boolean5 == boolean4);
      assertFalse(boolean5);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(3, board0.getSize());
      assertEquals(16, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      String string1 = board_Position0.toString();
      assertTrue(string1.equals((Object)string0));
      assertEquals("(0, 3)", string1);
      assertNotNull(string1);
      assertEquals(0, board_Position0.row);
      assertEquals(3, board_Position0.col);
      
      String string2 = board_Position0.toString();
      assertTrue(string2.equals((Object)string1));
      assertTrue(string2.equals((Object)string0));
      assertEquals("(0, 3)", string2);
      assertNotNull(string2);
      assertEquals(0, board_Position0.row);
      assertEquals(3, board_Position0.col);
      
      String string3 = board_Position0.toString();
      assertTrue(string3.equals((Object)string1));
      assertTrue(string3.equals((Object)string0));
      assertTrue(string3.equals((Object)string2));
      assertEquals("(0, 3)", string3);
      assertNotNull(string3);
      assertEquals(0, board_Position0.row);
      assertEquals(3, board_Position0.col);
      
      String string4 = board_Position0.toString();
      assertTrue(string4.equals((Object)string3));
      assertTrue(string4.equals((Object)string2));
      assertTrue(string4.equals((Object)string1));
      assertTrue(string4.equals((Object)string0));
      assertEquals("(0, 3)", string4);
      assertNotNull(string4);
      assertEquals(0, board_Position0.row);
      assertEquals(3, board_Position0.col);
      
      String string5 = board_Position0.toString();
      assertTrue(string5.equals((Object)string3));
      assertTrue(string5.equals((Object)string4));
      assertTrue(string5.equals((Object)string2));
      assertTrue(string5.equals((Object)string0));
      assertTrue(string5.equals((Object)string1));
      assertEquals("(0, 3)", string5);
      assertNotNull(string5);
      assertEquals(0, board_Position0.row);
      assertEquals(3, board_Position0.col);
      
      boolean boolean6 = board0.moveLeft();
      assertFalse(boolean6 == boolean3);
      assertFalse(boolean6 == boolean2);
      assertTrue(boolean6 == boolean1);
      assertTrue(boolean6 == boolean5);
      assertFalse(boolean6 == boolean0);
      assertFalse(boolean6 == boolean4);
      assertFalse(boolean6);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(3, board0.getSize());
      assertEquals(16, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean7 = board_Position0.equals(board0);
      assertFalse(boolean7 == boolean0);
      assertTrue(boolean7 == boolean6);
      assertTrue(boolean7 == boolean5);
      assertTrue(boolean7 == boolean1);
      assertFalse(boolean7 == boolean4);
      assertFalse(boolean7 == boolean3);
      assertFalse(boolean7 == boolean2);
      assertFalse(boolean7);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(3, board0.getSize());
      assertEquals(16, board0.getScore());
      assertEquals(0, board_Position0.row);
      assertEquals(3, board_Position0.col);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean8 = board0.hasEmptyCells();
      assertFalse(boolean8 == boolean5);
      assertFalse(boolean8 == boolean6);
      assertTrue(boolean8 == boolean2);
      assertTrue(boolean8 == boolean0);
      assertFalse(boolean8 == boolean1);
      assertTrue(boolean8 == boolean4);
      assertFalse(boolean8 == boolean7);
      assertTrue(boolean8 == boolean3);
      assertTrue(boolean8);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(3, board0.getSize());
      assertEquals(16, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      int int0 = board0.getScore();
      assertEquals(16, int0);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(3, board0.getSize());
      assertEquals(16, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean9 = board0.isWinningBoard();
      assertFalse(boolean9 == boolean0);
      assertTrue(boolean9 == boolean7);
      assertTrue(boolean9 == boolean5);
      assertFalse(boolean9 == boolean4);
      assertFalse(boolean9 == boolean2);
      assertFalse(boolean9 == boolean3);
      assertTrue(boolean9 == boolean1);
      assertTrue(boolean9 == boolean6);
      assertFalse(boolean9 == boolean8);
      assertFalse(boolean9);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(3, board0.getSize());
      assertEquals(16, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean10 = board0.repOK();
      assertFalse(boolean10 == boolean1);
      assertTrue(boolean10 == boolean4);
      assertTrue(boolean10 == boolean8);
      assertFalse(boolean10 == boolean9);
      assertTrue(boolean10 == boolean0);
      assertFalse(boolean10 == boolean6);
      assertFalse(boolean10 == boolean7);
      assertFalse(boolean10 == boolean5);
      assertTrue(boolean10 == boolean3);
      assertTrue(boolean10 == boolean2);
      assertTrue(boolean10);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(3, board0.getSize());
      assertEquals(16, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean11 = board0.repOK();
      assertTrue(boolean11 == boolean4);
      assertFalse(boolean11 == boolean7);
      assertFalse(boolean11 == boolean9);
      assertFalse(boolean11 == boolean1);
      assertTrue(boolean11 == boolean0);
      assertTrue(boolean11 == boolean10);
      assertTrue(boolean11 == boolean2);
      assertTrue(boolean11 == boolean3);
      assertFalse(boolean11 == boolean6);
      assertTrue(boolean11 == boolean8);
      assertFalse(boolean11 == boolean5);
      assertTrue(boolean11);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(3, board0.getSize());
      assertEquals(16, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      // Undeclared exception!
      try { 
        board0.getCell(0, 3);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 3) is out of bounds for board size 3
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Board board0 = new Board(3);
      assertNotNull(board0);
      assertEquals(3, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean0 = board0.moveDown();
      assertTrue(boolean0);
      assertEquals(3, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean1 = board0.isFull();
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
      assertEquals(3, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean2 = board0.moveLeft();
      assertTrue(boolean2 == boolean0);
      assertFalse(boolean2 == boolean1);
      assertTrue(boolean2);
      assertEquals(4, board0.getScore());
      assertEquals(3, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertNotNull(set0);
      assertEquals(4, board0.getScore());
      assertEquals(3, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertFalse(set0.isEmpty());
      assertEquals(6, set0.size());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean3 = board0.moveDown();
      assertFalse(boolean3 == boolean0);
      assertTrue(boolean3 == boolean1);
      assertFalse(boolean3 == boolean2);
      assertFalse(boolean3);
      assertEquals(4, board0.getScore());
      assertEquals(3, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      // Undeclared exception!
      try { 
        Board.Direction.valueOf("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant ar.edu.unrc.game2048.Board.Direction.
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Board board0 = new Board();
      assertNotNull(board0);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      boolean boolean0 = board0.moveRight();
      assertTrue(boolean0);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      boolean boolean1 = board0.isLosingBoard();
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      boolean boolean2 = board0.moveLeft();
      assertTrue(boolean2 == boolean0);
      assertFalse(boolean2 == boolean1);
      assertTrue(boolean2);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      int int0 = board0.getScore();
      assertEquals(4, int0);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      // Undeclared exception!
      try { 
        Board.Direction.valueOf("7PD,jy");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant ar.edu.unrc.game2048.Board.Direction.7PD,jy
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Board board0 = new Board(1);
      assertNotNull(board0);
      assertTrue(board0.repOK());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      int int0 = 4;
      boolean boolean0 = board0.moveLeft();
      assertFalse(boolean0);
      assertTrue(board0.repOK());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean1 = board0.isFull();
      assertFalse(boolean1 == boolean0);
      assertTrue(boolean1);
      assertTrue(board0.repOK());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean2 = board0.hasEmptyCells();
      assertTrue(boolean2 == boolean0);
      assertFalse(boolean2 == boolean1);
      assertFalse(boolean2);
      assertTrue(board0.repOK());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      // Undeclared exception!
      try { 
        board0.getCell(4, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, 4) is out of bounds for board size 1
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(64, 64);
      assertNotNull(board_Position0);
      assertEquals(64, board_Position0.row);
      assertEquals(64, board_Position0.col);
      
      Board board0 = null;
      try {
        board0 = new Board(64, (AddTileStrategy) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Board board0 = new Board();
      assertNotNull(board0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      Board board1 = new Board(board0);
      assertTrue(board1.equals((Object)board0));
      assertNotNull(board1);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board1.repOK());
      assertFalse(board1.isWinningBoard());
      assertEquals(4, board1.getSize());
      assertEquals(0, board1.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean0 = board0.moveLeft();
      assertFalse(board0.equals((Object)board1));
      assertNotSame(board0, board1);
      assertTrue(boolean0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      String string0 = board0.toString();
      assertFalse(board0.equals((Object)board1));
      assertNotSame(board0, board1);
      assertEquals("Score: 0\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|    2|     |     |     |\n+-----+-----+-----+-----+\n|    2|    2|     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n", string0);
      assertNotNull(string0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertFalse(board0.equals((Object)board1));
      assertNotSame(board0, board1);
      assertNotNull(set0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertFalse(set0.isEmpty());
      assertEquals(13, set0.size());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean1 = board1.isWinningBoard();
      assertFalse(board0.equals((Object)board1));
      assertFalse(board1.equals((Object)board0));
      assertFalse(boolean1 == boolean0);
      assertNotSame(board0, board1);
      assertNotSame(board1, board0);
      assertFalse(boolean1);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board1.repOK());
      assertFalse(board1.isWinningBoard());
      assertEquals(4, board1.getSize());
      assertEquals(0, board1.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean2 = board1.moveUp();
      assertFalse(board0.equals((Object)board1));
      assertFalse(board1.equals((Object)board0));
      assertTrue(boolean2 == boolean0);
      assertFalse(boolean2 == boolean1);
      assertNotSame(board0, board1);
      assertNotSame(board1, board0);
      assertTrue(boolean2);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board1.repOK());
      assertFalse(board1.isWinningBoard());
      assertEquals(4, board1.getSize());
      assertEquals(0, board1.getScore());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      Cell cell0 = Cell.EMPTY;
      assertNotNull(cell0);
      assertTrue(cell0.isEmpty());
      assertTrue(cell0.repOK());
      assertEquals(".", cell0.toString());
      assertEquals(0, cell0.getValue());
      
      // Undeclared exception!
      try { 
        board1.setCell((-2266), 0, cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-2266, 0) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((Board) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(2, 2277);
      assertNotNull(board_Position0);
      assertEquals(2277, board_Position0.col);
      assertEquals(2, board_Position0.row);
      
      AddRandomTile addRandomTile0 = new AddRandomTile();
      assertNotNull(addRandomTile0);
      
      Board board0 = new Board(2, addRandomTile0);
      assertNotNull(board0);
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(2, board0.getSize());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertNotNull(set0);
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(2, board0.getSize());
      assertFalse(set0.isEmpty());
      assertEquals(2, set0.size());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertFalse(set0.contains(board_Position0));
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Board board0 = new Board();
      assertNotNull(board0);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      int int0 = board0.getSize();
      assertEquals(4, int0);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Board board0 = new Board(2789);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-1), (-1));
      assertNotNull(board_Position0);
      assertEquals((-1), board_Position0.col);
      assertEquals((-1), board_Position0.row);
      
      String string0 = board_Position0.toString();
      assertEquals("(-1, -1)", string0);
      assertNotNull(string0);
      assertEquals((-1), board_Position0.col);
      assertEquals((-1), board_Position0.row);
      
      boolean boolean0 = board_Position0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals((-1), board_Position0.col);
      assertEquals((-1), board_Position0.row);
      
      Board board0 = new Board();
      assertNotNull(board0);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      Board board1 = new Board(board0);
      assertTrue(board1.equals((Object)board0));
      assertNotNull(board1);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertTrue(board1.repOK());
      assertEquals(0, board1.getScore());
      assertEquals(4, board1.getSize());
      assertFalse(board1.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      boolean boolean1 = board1.moveLeft();
      assertFalse(board0.equals((Object)board1));
      assertFalse(board1.equals((Object)board0));
      assertFalse(boolean1 == boolean0);
      assertNotSame(board0, board1);
      assertNotSame(board1, board0);
      assertTrue(boolean1);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertTrue(board1.repOK());
      assertEquals(0, board1.getScore());
      assertEquals(4, board1.getSize());
      assertFalse(board1.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      String string1 = board1.toString();
      assertFalse(board0.equals((Object)board1));
      assertFalse(board1.equals((Object)board0));
      assertFalse(string1.equals((Object)string0));
      assertNotSame(board0, board1);
      assertNotSame(board1, board0);
      assertEquals("Score: 0\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|    2|     |     |     |\n+-----+-----+-----+-----+\n|    2|    2|     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n", string1);
      assertNotNull(string1);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertTrue(board1.repOK());
      assertEquals(0, board1.getScore());
      assertEquals(4, board1.getSize());
      assertFalse(board1.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      // Undeclared exception!
      try { 
        board1.getCell(3, 1510);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (3, 1510) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Board board0 = new Board();
      assertNotNull(board0);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      boolean boolean0 = board0.moveUp();
      assertTrue(boolean0);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      int int0 = board0.getScore();
      assertEquals(0, int0);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      Object object0 = new Object();
      assertNotNull(object0);
      
      boolean boolean1 = board0.equals(object0);
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      int int1 = board0.hashCode();
      assertFalse(int1 == int0);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      boolean boolean2 = board0.hasEmptyCells();
      assertTrue(boolean2 == boolean0);
      assertFalse(boolean2 == boolean1);
      assertTrue(boolean2);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      Board.Position board_Position0 = new Board.Position(4, 0);
      assertNotNull(board_Position0);
      assertEquals(4, board_Position0.row);
      assertEquals(0, board_Position0.col);
      
      String string0 = board_Position0.toString();
      assertEquals("(4, 0)", string0);
      assertNotNull(string0);
      assertEquals(4, board_Position0.row);
      assertEquals(0, board_Position0.col);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Board board0 = new Board();
      assertNotNull(board0);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      // Undeclared exception!
      try { 
        board0.getCell(0, (-1));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, -1) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Board board0 = new Board();
      assertNotNull(board0);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      board0.hashCode();
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      Cell cell0 = Cell.EMPTY;
      assertNotNull(cell0);
      assertEquals(".", cell0.toString());
      assertTrue(cell0.isEmpty());
      assertTrue(cell0.repOK());
      assertEquals(0, cell0.getValue());
      
      board0.setCell(2, 2, cell0);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(".", cell0.toString());
      assertTrue(cell0.isEmpty());
      assertTrue(cell0.repOK());
      assertEquals(0, cell0.getValue());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertNotNull(set0);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertFalse(set0.isEmpty());
      assertEquals(14, set0.size());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      Set<Board.Position> set1 = board0.getEmptyPositions();
      assertTrue(set1.equals((Object)set0));
      assertNotSame(set1, set0);
      assertNotNull(set1);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertFalse(set1.isEmpty());
      assertEquals(14, set1.size());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      boolean boolean0 = board0.isFull();
      assertFalse(boolean0);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      boolean boolean1 = board0.moveLeft();
      assertFalse(boolean1 == boolean0);
      assertTrue(boolean1);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      boolean boolean2 = board0.moveLeft();
      assertTrue(boolean2 == boolean1);
      assertFalse(boolean2 == boolean0);
      assertTrue(boolean2);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      board0.hashCode();
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      String string0 = board0.toString();
      assertEquals("Score: 4\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|    2|     |     |     |\n+-----+-----+-----+-----+\n|    4|    2|     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n", string0);
      assertNotNull(string0);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      Board.Position board_Position0 = new Board.Position(2, 2017);
      assertNotNull(board_Position0);
      assertEquals(2, board_Position0.row);
      assertEquals(2017, board_Position0.col);
      
      Object object0 = new Object();
      assertNotNull(object0);
      
      boolean boolean3 = board_Position0.equals(object0);
      assertFalse(boolean3 == boolean2);
      assertFalse(boolean3 == boolean1);
      assertTrue(boolean3 == boolean0);
      assertFalse(boolean3);
      assertEquals(2, board_Position0.row);
      assertEquals(2017, board_Position0.col);
      
      boolean boolean4 = board0.moveUp();
      assertFalse(boolean4 == boolean3);
      assertTrue(boolean4 == boolean1);
      assertFalse(boolean4 == boolean0);
      assertTrue(boolean4 == boolean2);
      assertTrue(boolean4);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      // Undeclared exception!
      try { 
        board0.getCell(0, 337);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 337) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Board board0 = new Board();
      assertNotNull(board0);
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      // Undeclared exception!
      try { 
        board0.getCell(1, (-2060));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (1, -2060) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-1507), (-1));
      assertNotNull(board_Position0);
      assertEquals((-1), board_Position0.col);
      assertEquals((-1507), board_Position0.row);
      
      boolean boolean0 = board_Position0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals((-1), board_Position0.col);
      assertEquals((-1507), board_Position0.row);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Board board0 = new Board();
      assertNotNull(board0);
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean0 = board0.isFull();
      assertFalse(boolean0);
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean1 = board0.hasEmptyCells();
      assertFalse(boolean1 == boolean0);
      assertTrue(boolean1);
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean2 = board0.isWinningBoard();
      assertTrue(boolean2 == boolean0);
      assertFalse(boolean2 == boolean1);
      assertFalse(boolean2);
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      // Undeclared exception!
      try { 
        board0.setCell((-1317), (-1), (Cell) null);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-1317, -1) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Board board0 = new Board();
      assertNotNull(board0);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      Cell cell0 = Cell.EMPTY;
      assertNotNull(cell0);
      assertEquals(".", cell0.toString());
      assertTrue(cell0.repOK());
      assertEquals(0, cell0.getValue());
      assertTrue(cell0.isEmpty());
      
      board0.setCell(1, 1, cell0);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(".", cell0.toString());
      assertTrue(cell0.repOK());
      assertEquals(0, cell0.getValue());
      assertTrue(cell0.isEmpty());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      boolean boolean0 = board0.isFull();
      assertFalse(boolean0);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      String string0 = board0.toString();
      assertEquals("Score: 0\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|    2|     |     |     |\n+-----+-----+-----+-----+\n|     |    2|     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n", string0);
      assertNotNull(string0);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      board0.hashCode();
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Board board0 = new Board(1);
      assertNotNull(board0);
      assertFalse(board0.isWinningBoard());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      boolean boolean0 = board0.isWinningBoard();
      assertFalse(boolean0);
      assertFalse(board0.isWinningBoard());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      Cell cell0 = Cell.EMPTY;
      assertNotNull(cell0);
      assertTrue(cell0.isEmpty());
      assertEquals(".", cell0.toString());
      assertTrue(cell0.repOK());
      assertEquals(0, cell0.getValue());
      
      // Undeclared exception!
      try { 
        board0.setCell(579, 0, cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (579, 0) is out of bounds for board size 1
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Board board0 = new Board();
      assertNotNull(board0);
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      boolean boolean0 = board0.repOK();
      assertTrue(boolean0);
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      AddRandomTile addRandomTile0 = new AddRandomTile();
      assertNotNull(addRandomTile0);
      
      Board board0 = null;
      try {
        board0 = new Board(0, addRandomTile0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: 0
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Board board0 = new Board();
      assertNotNull(board0);
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      
      int int0 = 4;
      Board board1 = new Board(board0);
      assertTrue(board1.equals((Object)board0));
      assertNotNull(board1);
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board1.isWinningBoard());
      assertTrue(board1.repOK());
      assertEquals(4, board1.getSize());
      assertEquals(0, board1.getScore());
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      
      // Undeclared exception!
      try { 
        board1.getCell(0, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      AddTileDeterministic addTileDeterministic0 = new AddTileDeterministic();
      Board board0 = new Board(985, addTileDeterministic0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Board board0 = new Board();
      board0.hasEmptyCells();
      board0.moveUp();
      board0.hashCode();
      board0.moveDown();
      board0.toString();
      Object object0 = new Object();
      board0.equals(object0);
      board0.hashCode();
      assertEquals(4, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Board board0 = new Board();
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertTrue(board0.repOK());
      assertEquals(14, set0.size());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Board board0 = new Board();
      board0.isLosingBoard();
      board0.getEmptyPositions();
      Board board1 = new Board(board0);
      board1.moveDown();
      board0.getEmptyPositions();
      board1.moveRight();
      board0.getEmptyPositions();
      board1.moveLeft();
      board1.isLosingBoard();
      // Undeclared exception!
      try { 
        board1.getCell(4, 2048);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, 2048) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Board board0 = new Board();
      board0.isWinningBoard();
      Board.Position board_Position0 = new Board.Position(2048, 1236);
      String string0 = board_Position0.toString();
      assertEquals("(2048, 1236)", string0);
      
      board_Position0.equals(board0);
      boolean boolean0 = board0.moveUp();
      assertTrue(boolean0);
      
      int int0 = board0.getScore();
      assertEquals(0, int0);
      assertTrue(board0.repOK());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Board board0 = new Board();
      board0.moveRight();
      board0.isLosingBoard();
      // Undeclared exception!
      try { 
        Board.Direction.valueOf("7PD,jy");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant ar.edu.unrc.game2048.Board.Direction.7PD,jy
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Board board0 = new Board();
      board0.isLosingBoard();
      board0.getEmptyPositions();
      int int0 = 741;
      // Undeclared exception!
      try { 
        board0.getCell(741, 719);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (741, 719) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Board board0 = new Board();
      int int0 = 0;
      // Undeclared exception!
      try { 
        board0.setCell(0, 0, (Cell) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell cannot be null
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Board board0 = new Board();
      board0.hasEmptyCells();
      board0.moveLeft();
      board0.moveDown();
      board0.hasEmptyCells();
      Board.Direction.values();
      board0.getCell(3, 3);
      assertEquals(4, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Board board0 = new Board();
      String string0 = board0.toString();
      assertEquals("Score: 0\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|    2|     |     |     |\n+-----+-----+-----+-----+\n|     |    2|     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n", string0);
      
      boolean boolean0 = board0.moveLeft();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: 0
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      AddRandomTile addRandomTile0 = new AddRandomTile();
      Board board0 = null;
      try {
        board0 = new Board((-2660), addRandomTile0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -2660
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Board board0 = new Board();
      board0.moveDown();
      board0.getEmptyPositions();
      board0.isWinningBoard();
      board0.repOK();
      Board.Direction.values();
      board0.getScore();
      Board.Position board_Position0 = new Board.Position(2048, 2048);
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board0.isFull();
      Object object0 = null;
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board0.hashCode();
      // Undeclared exception!
      try { 
        board0.getCell((-2160), 419);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-2160, 419) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Board board0 = new Board(3);
      board0.moveDown();
      board0.isFull();
      board0.moveLeft();
      board0.getEmptyPositions();
      board0.repOK();
      // Undeclared exception!
      try { 
        Board.Direction.valueOf(":^");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant ar.edu.unrc.game2048.Board.Direction.:^
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Board board0 = new Board();
      board0.hasEmptyCells();
      board0.moveLeft();
      board0.moveUp();
      board0.hashCode();
      board0.hashCode();
      board0.toString();
      Object object0 = new Object();
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      // Undeclared exception!
      try { 
        Board.Direction.valueOf("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant ar.edu.unrc.game2048.Board.Direction.
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Board board0 = new Board();
      board0.getScore();
      Board.Position board_Position0 = new Board.Position(1953, 1204);
      board_Position0.equals(board0);
      board0.isFull();
      board0.isLosingBoard();
      // Undeclared exception!
      try { 
        board0.getCell((-944), (-944));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-944, -944) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, 3);
      Board board0 = new Board(3);
      board0.moveDown();
      board0.isLosingBoard();
      board_Position0.toString();
      board0.moveRight();
      board0.moveLeft();
      board0.moveDown();
      board0.isLosingBoard();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board0.moveLeft();
      board_Position0.equals(board0);
      board0.hasEmptyCells();
      board0.getScore();
      board0.isWinningBoard();
      board0.repOK();
      board0.repOK();
      int int0 = 0;
      // Undeclared exception!
      try { 
        board0.getCell(0, 17);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 17) is out of bounds for board size 3
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      AddRandomTile addRandomTile0 = new AddRandomTile();
      Board board0 = new Board(455, addRandomTile0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Board.Direction.values();
      Board board0 = new Board();
      board0.isLosingBoard();
      board0.moveDown();
      Board.Position board_Position0 = new Board.Position(2048, 3775);
      Object object0 = new Object();
      board_Position0.equals(object0);
      Board.Direction.values();
      board0.moveDown();
      board0.repOK();
      board0.isWinningBoard();
      // Undeclared exception!
      try { 
        Board.Direction.valueOf("ar.edu.unrc.game2048.AddTileDeterministic");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant ar.edu.unrc.game2048.Board.Direction.ar.edu.unrc.game2048.AddTileDeterministic
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Board board0 = new Board(1);
      board0.isFull();
      board0.isLosingBoard();
      board0.hashCode();
      board0.isFull();
      board0.isLosingBoard();
      board0.hasEmptyCells();
      Cell cell0 = Cell.EMPTY;
      board0.hashCode();
      board0.moveDown();
      board0.isLosingBoard();
      Board board1 = new Board(3);
      board0.equals(board1);
      Board.Position board_Position0 = new Board.Position(4, (-2499));
      Board.Position board_Position1 = new Board.Position(4, 1799);
      board_Position0.equals(board_Position1);
      // Undeclared exception!
      try { 
        board0.getCell(19, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (19, 4) is out of bounds for board size 1
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }
}
