/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 24 18:07:32 GMT 2026
 */

package ar.edu.unrc.game2048;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ar.edu.unrc.game2048.AddRandomTile;
import ar.edu.unrc.game2048.AddTileDeterministic;
import ar.edu.unrc.game2048.AddTileStrategy;
import ar.edu.unrc.game2048.Board;
import ar.edu.unrc.game2048.Cell;
import java.util.LinkedHashSet;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class Board_ESTest extends Board_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Board board0 = new Board(1);
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertEquals(0, set0.size());
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      
      board0.hasEmptyCells();
      board0.getScore();
      board0.getSize();
      board0.moveDown();
      // Undeclared exception!
      try { 
        board0.getCell((-1), 0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-1, 0) is out of bounds for board size 1
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Board board0 = new Board(43);
      board0.moveDown();
      board0.moveDown();
      board0.repOK();
      board0.hasEmptyCells();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int int0 = 1;
      AddRandomTile addRandomTile0 = new AddRandomTile();
      Board board0 = new Board(1, addRandomTile0);
      board0.repOK();
      Board.Direction.values();
      board0.moveRight();
      board0.repOK();
      board0.moveUp();
      // Undeclared exception!
      try { 
        board0.getCell(4, 1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, 1) is out of bounds for board size 1
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board(21, (AddTileStrategy) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Board board0 = new Board(43);
      board0.moveDown();
      board0.repOK();
      board0.hasEmptyCells();
      board0.toString();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Board board0 = new Board(43);
      board0.isLosingBoard();
      board0.moveDown();
      board0.getEmptyPositions();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Board board0 = new Board(43);
      board0.moveDown();
      board0.isLosingBoard();
      board0.hasEmptyCells();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int int0 = 1;
      Board board0 = new Board(1);
      board0.toString();
      board0.isFull();
      board0.isFull();
      int int1 = 0;
      Cell cell0 = Cell.EMPTY;
      // Undeclared exception!
      try { 
        board0.getCell(1, 1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (1, 1) is out of bounds for board size 1
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = new Cell(0);
      board0.setCell(0, 0, cell0);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.isFull();
      boolean boolean1 = board0.repOK();
      assertFalse(boolean1 == boolean0);
      
      int int0 = board0.getScore();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      int int0 = 3;
      Board board0 = new Board(3);
      Board board1 = new Board(board0);
      board1.hashCode();
      int int1 = 1031;
      board0.isLosingBoard();
      // Undeclared exception!
      try { 
        board1.getCell(4, 1031);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, 1031) is out of bounds for board size 3
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      int int0 = 3;
      Board.Position board_Position0 = new Board.Position(3, 3);
      board_Position0.toString();
      board_Position0.toString();
      Board.Position board_Position1 = new Board.Position(660, 660);
      board_Position0.toString();
      board_Position1.toString();
      board_Position1.toString();
      board_Position1.toString();
      board_Position0.equals(board_Position1);
      AddRandomTile addRandomTile0 = new AddRandomTile();
      Cell[][] cellArray0 = new Cell[7][1];
      Cell[] cellArray1 = new Cell[1];
      Cell cell0 = null;
      try {
        cell0 = new Cell(3);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell must be a power of two: 3
         //
         verifyException("ar.edu.unrc.game2048.Cell", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Board board0 = new Board();
      board0.hashCode();
      board0.moveLeft();
      board0.isLosingBoard();
      board0.toString();
      // Undeclared exception!
      try { 
        board0.getCell(0, 10);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 10) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.setCell(1, 4, (Cell) null);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (1, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Board.Direction.values();
      Board.Position board_Position0 = new Board.Position(0, 0);
      Board.Position board_Position1 = new Board.Position(0, 1692);
      board_Position1.toString();
      board_Position1.toString();
      board_Position0.toString();
      board_Position1.toString();
      board_Position0.equals(board_Position1);
      board_Position1.toString();
      Board board0 = null;
      try {
        board0 = new Board(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: 0
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-708), 338);
      board_Position0.toString();
      Board.Position board_Position1 = new Board.Position((-708), 0);
      board_Position0.equals(board_Position1);
      Board board0 = null;
      try {
        board0 = new Board((Board) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      int int0 = 1481;
      AddTileDeterministic addTileDeterministic0 = new AddTileDeterministic();
      LinkedHashSet<Board.Position> linkedHashSet0 = new LinkedHashSet<Board.Position>();
      addTileDeterministic0.addTile((Cell[][]) null, linkedHashSet0);
      LinkedHashSet<Board.Position> linkedHashSet1 = new LinkedHashSet<Board.Position>();
      addTileDeterministic0.addTile((Cell[][]) null, linkedHashSet1);
      Board board0 = new Board(1481, addTileDeterministic0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      // Undeclared exception!
      try { 
        board1.getCell(4, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Board board0 = new Board();
      board0.moveUp();
      board0.hashCode();
      board0.getEmptyPositions();
      board0.moveUp();
      board0.moveLeft();
      board0.isWinningBoard();
      board0.isLosingBoard();
      String string0 = "Ewn";
      // Undeclared exception!
      try { 
        Board.Direction.valueOf("Ewn");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant ar.edu.unrc.game2048.Board.Direction.Ewn
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(1, 0);
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      Board board0 = new Board(1);
      board_Position0.toString();
      int int0 = board0.getSize();
      assertEquals(1, int0);
      
      boolean boolean0 = board0.isLosingBoard();
      Board.Direction.values();
      board_Position0.toString();
      board0.equals("(1, 0)");
      board0.moveRight();
      boolean boolean1 = board0.isFull();
      board0.isLosingBoard();
      boolean boolean2 = board0.isWinningBoard();
      assertFalse(boolean2 == boolean1);
      
      String string0 = board_Position0.toString();
      assertEquals("(1, 0)", string0);
      
      boolean boolean3 = board0.moveRight();
      assertFalse(boolean3 == boolean0);
      
      board0.equals((Object) null);
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.hasEmptyCells();
      assertTrue(boolean0);
      
      String string0 = board0.toString();
      assertEquals("Score: 0\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|    2|     |     |     |\n+-----+-----+-----+-----+\n|     |    2|     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n", string0);
      assertTrue(board0.repOK());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Board board0 = new Board();
      board0.moveDown();
      board0.hasEmptyCells();
      board0.moveUp();
      board0.moveRight();
      board0.moveUp();
      board0.hashCode();
      board0.repOK();
      // Undeclared exception!
      try { 
        board0.setCell(0, 0, (Cell) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell cannot be null
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = board0.getCell(0, 0);
      assertEquals(".", cell0.toString());
      
      int int0 = board0.getSize();
      assertEquals(4, int0);
      assertTrue(board0.repOK());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-1738), (-1738));
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.equals((Object) null);
      Board board0 = new Board(1);
      // Undeclared exception!
      try { 
        board0.getCell((-1738), (-1738));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-1738, -1738) is out of bounds for board size 1
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(1, 0);
      board_Position0.toString();
      board_Position0.equals((Object) null);
      Board board0 = null;
      try {
        board0 = new Board(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: 0
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      AddRandomTile addRandomTile0 = new AddRandomTile();
      Board board0 = new Board(3, addRandomTile0);
      assertTrue(board0.repOK());
      assertEquals(3, board0.getSize());
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Board board0 = new Board(4);
      board0.isFull();
      int int0 = Board.DEFAULT_SIZE;
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.moveRight();
      assertTrue(boolean0);
      assertEquals(0, board0.getScore());
      
      int int0 = board0.getSize();
      assertEquals(4, int0);
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-1741), (-1741));
      Board board0 = new Board();
      int int0 = (-620);
      Cell cell0 = Cell.EMPTY;
      int int1 = 1950;
      // Undeclared exception!
      try { 
        board0.setCell(0, (-1741), cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, -1741) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(1777, (-2748));
      board_Position0.toString();
      board_Position0.toString();
      AddRandomTile addRandomTile0 = new AddRandomTile();
      Board board0 = null;
      try {
        board0 = new Board((-2748), addRandomTile0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -2748
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((Board) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      int int0 = 3061;
      Board board0 = new Board(3061);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell(2, (-2407));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2, -2407) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((-812));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -812
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-3044), 3);
      board_Position0.toString();
      board_Position0.toString();
      Object object0 = new Object();
      board_Position0.equals(object0);
      AddRandomTile addRandomTile0 = new AddRandomTile();
      Board board0 = null;
      try {
        board0 = new Board((-3044), addRandomTile0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -3044
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      AddTileDeterministic addTileDeterministic0 = new AddTileDeterministic();
      Board board0 = new Board(3, addTileDeterministic0);
      board0.hashCode();
      Cell cell0 = null;
      try {
        cell0 = new Cell((-1003));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell value cannot be negative: -1003
         //
         verifyException("ar.edu.unrc.game2048.Cell", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      int int0 = 0;
      Board board0 = null;
      try {
        board0 = new Board(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: 0
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, 0);
      Board.Position board_Position1 = new Board.Position(0, 0);
      board_Position1.toString();
      board_Position1.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position1.toString();
      board_Position0.toString();
      board_Position1.toString();
      board_Position0.toString();
      board_Position1.toString();
      board_Position1.toString();
      board_Position0.toString();
      board_Position1.toString();
      board_Position0.equals(board_Position1);
      Board board0 = new Board();
      board0.hashCode();
      board0.moveUp();
      board0.hashCode();
      board0.moveLeft();
      board0.moveRight();
      board0.hashCode();
      board0.toString();
      assertEquals(4, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, 0);
      Board.Position board_Position1 = new Board.Position(0, 0);
      board_Position1.toString();
      board_Position1.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position1.toString();
      board_Position0.toString();
      board_Position1.toString();
      board_Position0.toString();
      board_Position1.toString();
      board_Position1.toString();
      board_Position0.toString();
      board_Position1.toString();
      board_Position0.equals(board_Position1);
      Board board0 = new Board();
      board0.hashCode();
      board0.moveUp();
      board0.hashCode();
      board0.moveLeft();
      board0.moveRight();
      int int0 = Board.DEFAULT_SIZE;
      board0.toString();
      assertEquals(4, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(1326, 1326);
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      Board board0 = new Board();
      board0.isFull();
      board0.isWinningBoard();
      board0.hashCode();
      board0.isWinningBoard();
      board0.equals("(1326, 1326)");
      // Undeclared exception!
      try { 
        board0.getCell((-3076), 820);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-3076, 820) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Board board0 = new Board();
      board0.isLosingBoard();
      board0.moveRight();
      board0.getEmptyPositions();
      board0.moveUp();
      board0.hasEmptyCells();
      board0.hasEmptyCells();
      board0.getScore();
      board0.moveUp();
      board0.getEmptyPositions();
      board0.moveRight();
      board0.getSize();
      board0.moveUp();
      board0.isFull();
      board0.hashCode();
      board0.equals("]f2-% r6a&2q=]D");
      int int0 = board0.getScore();
      assertEquals(16, int0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Board.Direction.values();
      Board board0 = new Board();
      board0.getEmptyPositions();
      board0.hashCode();
      board0.isLosingBoard();
      board0.moveUp();
      board0.hasEmptyCells();
      board0.moveRight();
      board0.isWinningBoard();
      board0.repOK();
      int int0 = 1114;
      // Undeclared exception!
      try { 
        board0.getCell(1114, 1114);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (1114, 1114) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Board board0 = new Board();
      board0.moveUp();
      board0.isLosingBoard();
      board0.getCell(0, 0);
      board0.isFull();
      board0.isLosingBoard();
      Board.Direction.values();
      board0.moveDown();
      Board.Position board_Position0 = new Board.Position(2048, 4);
      board_Position0.toString();
      // Undeclared exception!
      try { 
        board0.getCell(2048, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2048, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Board board0 = new Board();
      board0.isFull();
      board0.moveRight();
      board0.moveDown();
      Cell cell0 = new Cell(2048);
      board0.setCell(0, 0, cell0);
      board0.moveLeft();
      board0.isWinningBoard();
      board0.hashCode();
      board0.hasEmptyCells();
      board0.getEmptyPositions();
      board0.moveDown();
      board0.isFull();
      board0.isFull();
      board0.moveLeft();
      board0.hasEmptyCells();
      boolean boolean0 = board0.hasEmptyCells();
      assertEquals(16, board0.getScore());
      assertTrue(boolean0);
  }
}
