/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 25 20:06:41 GMT 2026
 */

package ar.edu.unrc.game2048;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ar.edu.unrc.game2048.Cell;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class Cell_ESTest extends Cell_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Cell cell0 = new Cell(2);
      Cell cell1 = Cell.EMPTY;
      boolean boolean0 = cell0.equals(cell1);
      assertFalse(boolean0);
      assertFalse(cell1.equals((Object)cell0));
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Cell cell0 = new Cell(2);
      Cell cell1 = new Cell(2);
      Cell cell2 = cell0.mergeWith(cell1);
      boolean boolean0 = cell2.canMergeWith(cell1);
      assertFalse(boolean0);
      assertEquals(4, cell2.getValue());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Cell cell0 = new Cell(2);
      int int0 = cell0.getValue();
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Cell cell0 = new Cell(2);
      String string0 = cell0.toString();
      assertEquals("2", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      String string0 = cell0.toString();
      assertEquals(".", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Cell cell0 = new Cell(2);
      Cell cell1 = new Cell(2);
      boolean boolean0 = cell0.canMergeWith(cell1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Cell cell0 = new Cell(0);
      Cell cell1 = new Cell(0);
      boolean boolean0 = cell0.canMergeWith(cell1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Cell cell0 = new Cell(2);
      boolean boolean0 = cell0.canMergeWith(cell0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Cell cell0 = new Cell(0);
      boolean boolean0 = cell0.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Cell cell0 = new Cell(2);
      boolean boolean0 = cell0.isEmpty();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      boolean boolean0 = cell0.repOK();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Cell cell0 = new Cell(8);
      boolean boolean0 = cell0.repOK();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Cell cell0 = new Cell(2);
      // Undeclared exception!
      try { 
        cell0.mergeWith(cell0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot merge cells: 2 and 2
         //
         verifyException("ar.edu.unrc.game2048.Cell", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Cell cell0 = new Cell(8);
      Cell cell1 = new Cell(8);
      boolean boolean0 = cell0.equals(cell1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      boolean boolean0 = cell0.equals("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Cell cell0 = new Cell(0);
      boolean boolean0 = cell0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Cell cell0 = new Cell(8);
      boolean boolean0 = cell0.equals(cell0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Cell cell0 = new Cell(8);
      Cell cell1 = new Cell(8);
      Cell cell2 = cell0.mergeWith(cell1);
      boolean boolean0 = cell0.equals(cell2);
      assertTrue(cell1.equals((Object)cell0));
      assertEquals("16", cell2.toString());
      assertFalse(boolean0);
      assertFalse(cell2.equals((Object)cell1));
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Cell cell0 = new Cell(8);
      Cell cell1 = new Cell(0);
      boolean boolean0 = cell0.canMergeWith(cell1);
      assertFalse(boolean0);
      assertTrue(cell1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      boolean boolean0 = cell0.canMergeWith((Cell) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Cell cell0 = new Cell(8);
      Cell cell1 = new Cell(8);
      assertFalse(cell1.isEmpty());
      assertEquals(8, cell1.getValue());
      
      Cell cell2 = cell0.mergeWith(cell1);
      boolean boolean0 = cell0.canMergeWith(cell2);
      assertFalse(boolean0);
      assertEquals("16", cell2.toString());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Cell cell0 = null;
      try {
        cell0 = new Cell(2388);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell must be a power of two: 2388
         //
         verifyException("ar.edu.unrc.game2048.Cell", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Cell cell0 = null;
      try {
        cell0 = new Cell(1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell must be a power of two greater than 1: 1
         //
         verifyException("ar.edu.unrc.game2048.Cell", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Cell cell0 = null;
      try {
        cell0 = new Cell((-404));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell value cannot be negative: -404
         //
         verifyException("ar.edu.unrc.game2048.Cell", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Cell cell0 = new Cell(0);
      // Undeclared exception!
      try { 
        cell0.EMPTY.mergeWith(cell0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot merge cells: . and .
         //
         verifyException("ar.edu.unrc.game2048.Cell", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      int int0 = cell0.getValue();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      cell0.hashCode();
  }
}
