/*
 * This file was automatically generated by EvoSuite
 * Wed Sep 16 23:59:23 GMT 2026
 */

package ar.edu.unrc.game2048;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ar.edu.unrc.game2048.Cell;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Cell_ESTest extends Cell_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Cell cell0 = new Cell(8);
      assertEquals("8", cell0.toString());
      
      Cell cell1 = cell0.mergeWith(cell0);
      assertEquals(16, cell1.getValue());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Cell cell0 = new Cell(2);
      int int0 = cell0.getValue();
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      // Undeclared exception!
      try { 
        cell0.EMPTY.mergeWith((Cell) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.Cell", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      // Undeclared exception!
      try { 
        cell0.canMergeWith((Cell) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.Cell", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Cell cell0 = new Cell(2);
      String string0 = cell0.toString();
      assertEquals("2", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      String string0 = cell0.toString();
      assertEquals(".", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Cell cell0 = new Cell(8);
      cell0.canMergeWith(cell0);
      assertEquals(8, cell0.getValue());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      Cell cell1 = new Cell(8);
      boolean boolean0 = cell1.canMergeWith(cell0);
      assertEquals(8, cell1.getValue());
      assertTrue(cell0.isEmpty());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      Cell cell1 = new Cell(8);
      boolean boolean0 = cell0.canMergeWith(cell1);
      assertTrue(cell0.isEmpty());
      assertEquals("8", cell1.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      boolean boolean0 = cell0.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Cell cell0 = new Cell(2);
      cell0.isEmpty();
      assertEquals("2", cell0.toString());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      Cell cell1 = new Cell(8);
      boolean boolean0 = cell1.equals(cell0);
      assertEquals(8, cell1.getValue());
      assertFalse(boolean0);
      assertFalse(cell0.equals((Object)cell1));
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Cell cell0 = new Cell(0);
      Cell cell1 = new Cell(0);
      boolean boolean0 = cell0.equals(cell1);
      assertTrue(boolean0);
      assertTrue(cell1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      boolean boolean0 = cell0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Cell cell0 = new Cell(0);
      boolean boolean0 = cell0.equals(cell0);
      assertTrue(boolean0);
      assertEquals(".", cell0.toString());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Cell cell0 = new Cell(0);
      boolean boolean0 = cell0.equals("LdDX^a$:");
      assertFalse(boolean0);
      assertEquals(".", cell0.toString());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Cell cell0 = new Cell(2);
      assertFalse(cell0.isEmpty());
      
      Cell cell1 = cell0.mergeWith(cell0);
      boolean boolean0 = cell0.equals(cell1);
      assertFalse(boolean0);
      assertFalse(cell1.isEmpty());
      assertEquals(2, cell0.getValue());
      assertFalse(cell1.equals((Object)cell0));
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Cell cell0 = null;
      try {
        cell0 = new Cell(950);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell must be a power of two: 950
         //
         verifyException("ar.edu.unrc.game2048.Cell", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Cell cell0 = null;
      try {
        cell0 = new Cell(1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell must be a power of two greater than 1: 1
         //
         verifyException("ar.edu.unrc.game2048.Cell", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Cell cell0 = null;
      try {
        cell0 = new Cell((-65));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell value cannot be negative: -65
         //
         verifyException("ar.edu.unrc.game2048.Cell", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Cell cell0 = new Cell(0);
      boolean boolean0 = cell0.canMergeWith(cell0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      int int0 = cell0.getValue();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      cell0.hashCode();
  }
}
