/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 24 18:10:18 GMT 2026
 */

package ar.edu.unrc.game2048;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ar.edu.unrc.game2048.Board;
import ar.edu.unrc.game2048.Movement;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class Movement_ESTest extends Movement_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Board board0 = new Board();
      Movement.MoveResult movement_MoveResult0 = new Movement.MoveResult(board0, 4861);
      assertEquals(4861, movement_MoveResult0.scoreDelta);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Board board0 = new Board(26);
      board0.moveRight();
      Board.Direction board_Direction0 = Board.Direction.RIGHT;
      board0.moveUp();
      board0.moveRight();
      Movement.MoveResult movement_MoveResult0 = Movement.move(board0, board_Direction0);
      Movement.MoveResult movement_MoveResult1 = Movement.move(movement_MoveResult0.board, board_Direction0);
      // Undeclared exception!
      Movement.move(movement_MoveResult1.board, board_Direction0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Board.Direction board_Direction0 = Board.Direction.RIGHT;
      // Undeclared exception!
      try { 
        Movement.move((Board) null, board_Direction0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Board board0 = new Board();
      Board.Direction board_Direction0 = Board.Direction.DOWN;
      Movement.MoveResult movement_MoveResult0 = Movement.move(board0, board_Direction0);
      Board.Direction board_Direction1 = Board.Direction.RIGHT;
      Movement.MoveResult movement_MoveResult1 = Movement.move(movement_MoveResult0.board, board_Direction1);
      assertEquals(4, movement_MoveResult1.scoreDelta);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.moveUp();
      assertTrue(boolean0);
      
      Board.Direction board_Direction0 = Board.Direction.DOWN;
      Movement.MoveResult movement_MoveResult0 = Movement.move(board0, board_Direction0);
      Board.Direction board_Direction1 = Board.Direction.LEFT;
      Movement.MoveResult movement_MoveResult1 = Movement.move(movement_MoveResult0.board, board_Direction1);
      assertEquals(0, movement_MoveResult1.scoreDelta);
      assertEquals(4, movement_MoveResult0.scoreDelta);
  }
}
